comentario/urls.py
from django.urls import path, include
from . import views

app_name="comentario"

urlpatterns = [
    path('<int:id>/novo', views.novo)
]

espacos/urls.py
from django.urls import path, include
from . import views

app_name="espacos"

urlpatterns = [
    path('', views.index, name="index"),
    path('bloco/', views.blocodefault, name="bloco_padrao" ),
    path('bloco/add/', views.add_bloco, name='add_bloco'),
    path('bloco/<int:id>/', views.bloco, name="bloco" ),
    path('piso/<int:id>/', views.piso, name="piso" ),
    path('sala/<int:id>/', views.sala, name='sala'),
    path('login_adm/', views.login_adm, name='login_adm'),
    path('cadastro_adm/', views.cadastro_adm, name='cadastro_adm'),  
]

iftour/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("espacos.urls")),
    path('comentario/', include("comentario.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comentario/models.py
from django.db import models
from espacos.models import Sala
# Create your models here.

class Avaliacao(models.Model):
    dt_cad = models.DateField(auto_now = True)
    comentario = models.TextField()
    nota = models.PositiveIntegerField()
    nome = models.TextField()
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE)

# def __str__(self):
#         return self.dt_cad

espacos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bloco(models.Model):
    nome = models.CharField(max_length=15, null=False, unique = True)
    legenda = models.TextField()
    imagem = models.ImageField(upload_to="blocos/")
   
    def __str__(self):
        return self.nome

class Piso(models.Model):
    nome = models.CharField(max_length=15, null=False, unique = True)
    bloco = models.ForeignKey(Bloco, on_delete=models.CASCADE)
    
    def get_salas(self):
        return Sala.objects.filter(piso__id = self.id)
    
    def __str__(self):
        return self.nome

class Sala(models.Model):
    nome = models.CharField(max_length=15, null=False, unique = True)
    legenda = models.TextField()
    imagem = models.ImageField("Thumbnail", upload_to="salas/")
    img_360 = models.ImageField(upload_to="360/", null=True)
    piso = models.ForeignKey(Piso, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome
    
class Administrador(models.Model):
    nome = models.CharField(max_length=15, null=False, unique = True)
    email = models.EmailField(unique=True)
    login = models.OneToOneField(User, on_delete=models.CASCADE)
    senha = models.CharField(max_length=128)
    foto = models.ImageField(upload_to="adms_img/", null=True)

    def __str__(self):
        return self.nome
    
    

comentario/views.py
from django.shortcuts import redirect, render
import comentario

from comentario.models import Avaliacao
from espacos.models import Sala
def novo(request, id):
    if request.POST:
        n = request.POST.get('nome')
        c = request.POST.get('comentario')
        a = int(request.POST.get('fb'))
        s = Sala.objects.get(pk = id)
        novo = Avaliacao(nome = n, comentario = c, nota = a, sala = s)
        novo.save()
        return redirect(f'/sala/{id}')
    else:
        return render(request, 'sala.html')

# Create your views here.

espacos/views.py
from http.client import HTTPResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from comentario.models import Avaliacao
from .models import Bloco, Piso, Sala, Administrador
from django.contrib.auth.models import User


def index(request):
    lista = Bloco.objects.all()
    return render(request, 'index.html', {"lista" : lista})


def add_bloco(request):
    return render(request, 'add_bloco.html')

def sala(request,id):
    s = Sala.objects.get(pk=id)
    comentarios = Avaliacao.objects.filter(sala = s)
    soma = 0
    for c in comentarios:
        soma += c.nota
    if len(comentarios) > 0:
        media = soma/len(comentarios)
    else:
        media = 0

    ctx = {
        'bloco' : s.piso.bloco,
        'piso' : s.piso,
        'sala' : s,
        'comentarios' : comentarios,
    }
    return render(request, 'sala.html',ctx)

def bloco(request, id):
    b = Bloco.objects.get(pk=id)
    blocos = Bloco.objects.all()
    pisos = Piso.objects.filter(bloco=b)
    ctx = {
        'bloco' : b,
        'blocos': blocos,
        'pisos' : pisos
    }
    return render(request, 'bloco.html', ctx)

def blocodefault(request):
    b = Bloco.objects.all()[0]
    print(b)
    return redirect(f'/bloco/{b.id}/')


# Create your views here.
def piso(request, id):
    p = Piso.objects.get(pk=id)
    pisos = Piso.objects.filter(bloco=p.bloco)
    salas = Sala.objects.filter(piso = p)
    ctx = {
        'blocos' : Bloco.objects.all(),
        'bloco' : p.bloco,
        'pisos' : pisos,
        'piso' : p,
        'salas' :salas
    }
    return render(request, 'bloco.html', ctx)

def cadastro_adm(request):
    if request.method == 'POST':
        login = request.POST['login']
        senha = request.POST['senha']
        email = request.POST['email']
        foto = request.FILES.get('foto')

        # Verifica se o usuário já existe
        if User.objects.filter(username=login).exists():
            print("nome de usuário já existente")
            pass
        else:
            # Cria o usuário e registra com adm
            user = User.objects.create_user(username=login, password=senha, email=email)
            administrador = Administrador(login=user, nome=login, email=email, senha=senha, foto=foto)
            administrador.save()

        user = authenticate(request, username=login, password=senha)
        if user is not None:
            login(request, user)
            return redirect('login_adm')
    else:
        # manda para o cadastro de adm
        form = UserCreationForm()
    return render(request, 'cadastro_adm.html', {'form': form})

def login_adm(request):
    if request.method == 'POST':
        login = request.POST['login']
        senha = request.POST['senha']
        user = authenticate(request, username=login, password=senha)
        if user is not None:
            login(request, user)
            return redirect('#') #dhasbord do administrador.
        else:
            print("Login ou senha incorretos")
            pass
    return render(request, 'login_adm.html')

espacos/templates/add_bloco.html
{%extends 'base.html'%}
{%load static %}
{%block conteudo%}
    <div class="container-fluid"> <!--Inicio container-->
        <div class="row header align-items-center"> <!--Inicio header-->
          <div class="col px-5"> <!--Inicio logo-->
            <a href="/"><img class="img-fluid" src="{% static '/img/logo.png'%}" alt="logo if-tour"></a>
          </div> <!--Fim logo--> 
        </div> <!--Fim header-->
        <div class="row v-full px-5 bg-verde align-items-start"> <!-- Inico conteudo-->
          <div class="col-12 col-md-12 col-lg-6 p-5"> <!-- Inico conteudo esquerdo-->
            <div class= "container-fluid"> <!-- Inicio form selecao sala -->
              <div class="row py-5">  <!-- Inicio 1ª linha form selecao sala -->
                <div class="col-12 col-sm-12 col-md-6 px-0 mx-0"> <!--Bloco Selec bloco-->
                    <select class="form-select form-select-lg mb-3 select-verde p-3" aria-label=".form-select-lg example" onchange="window.location.href=this.value">
                        <option value="{%url 'espacos:bloco_padrao'%}"> Selecione um bloco </option>
                          
                        {% for b in blocos %}
                          {%if b.id == bloco.id%}
                              <option selected value="{% url 'espacos:bloco' id=b.id %}"> {{b.nome}} </option>
                              {%else%}
                              <option value="{% url 'espacos:bloco' id=b.id %}"> {{b.nome}} </option>
                              {%endif%}
                          {% endfor %}
                      {%endfor}
                    </select>
                </div> <!--Fim bloco selec bloco-->
                <div class="col-12 col-sm-12 col-md-6 px-0 mx-0">  <!--Bloco Selec Piso-->
                      <select class="form-select form-select-lg mb-3 select-verdeclaro p-3" aria-label=".form-select-lg example" onchange="window.location.href=this.value">
                        <option value="{%url 'espacos:bloco_padrao'%}"> Selecione um piso </option>
                        {% for p in pisos %}
                            {%if p.id == piso.id%}
                            <option selected value="{% url 'espacos:piso' id=p.id %}"> {{p.nome}} </option>
                            {%else%}
                            <option value="{% url 'espacos:piso' id=p.id %}"> {{p.nome}} </option>
                            {%endif%}
                        {% endfor %}
                      </select> 
                </div>   <!--Fim bloco Selec Piso--> 
              </div>  <!-- Fim 1ª linha form selecao sala -->
              <div class="row"> <!-- Ini 2ª linha form selecao sala -->
                {%if bloco %}
                <div class="col mb-5">
                  <p class="h3">{{bloco.legenda}}</p>
                </div>
                {%endif%}
              </div> <!-- Fim 2ª linha form selecao sala -->
              <div class="row"> <!-- Ini 3ª linha form selecao sala -->
                {% if salas %}
                <fieldset class="container-fluid border mt-5">
                  <legend class="text-light legenda">Salas</legend>
                  <div class="row row-cols-auto justify-content-center text-center">
                    {% for s in salas %}
                    <div class="col mb-3 mt-3">
                      <a href="/sala/{{s.id}}"><img class="img-fluid img-thumbnail sla-thumb"
                        src="/media/{{s.imagem}}" alt=""> 
                      </a>  
                    </div>
                    {% endfor %}
                  </div>               
                {%else%}
                   <div class="col mb-3 mt-3">
                    <p>não há salas cadastradas neste piso</p>   
                   </div> 
                  </fieldset>
                {%endif%}  
              </div><!-- Fim 3ª linha form selecao sala -->
            </div><!-- Fim form selecao sala -->
          </div>  <!-- Fim conteudo esquerdo-->
          <div class="col-12 col-md-12 col-lg-6  align-middle my-auto"> <!-- Inico conteudo direito-->            
              <img src="/media/{{bloco.imagem}}" class="img-fluid mb-5 mx-3"/>
          </div>  <!-- Fim conteudo direito-->
        </div>  <!-- Fim conteudo-->
        <div class="row footer align-items-center"> <!--inicio footer-->
          <div class="col text-center px-5 text-light">
            &copy; 2022 - IF Tour
          </div>
        </div> <!--Fim footer-->     
    </div> <!--Fim container-->
{%endblock%}

espacos/templates/base.html
{%load static %}
<!DOCTYPE html>
<html>
    <!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="{% static '/css/bootstrap.min.css'%}" rel="stylesheet" type="text/css"/> <!--link do css do bootstrap-->

        <link href="{% static '/css/style.css'%}" rel="stylesheet" type="text/css"/> <!--link do css externo-->

        <link href="{% static '/css/bootstrap-icons.css'%}"> <!--link do bootstrap icons-->

        <link href="{% static '/fontawesome/css_fontawesome/all.min.css'%}"> <!--link do fontawesome, onde tem a estrelas da avaliação-->

        <script src="{% static 'js/aframe-master.min.js'%}"></script> <!--link do aframe-->
        <title>IF-TOUR</title>
    </head>
    <body>
         {%block conteudo%}{%endblock%}
    
        
        <script src="{% static 'js/bootstrap.bundle.min.js'%}" type="text/javascript"></script>
        <script src="{% static 'js/script.js'%}"></script>
        
    </body>
</html>

espacos/templates/bloco.html
{%extends 'base.html'%}
{%load static %}
{%block conteudo%}
    <div class="container-fluid"> <!--Inicio container-->
        <div class="row header align-items-center ptcima"> <!--Inicio header-->
          <div class="col-2 px-5"> <!--Inicio logo-->
            <a href="/"><img class="img-fluid" src="{% static '/img/logo.png'%}" alt="logo if-tour"></a>
          </div> <!--Fim logo--> 
          <div class="col-10 text-end">
            <a class="mx-4 text-dark" href="/">Inicio</a> <!--Ajeitar esse link aqui-->
            <a class="mx-4 text-dark" href="login_adm.html/">Entrar</a> <!--Ajeitar esse link aqui-->
            <a class="mx-4 text-dark" href="cadastro_adm.html/">Cadastrar</a> <!--Ajeitar esse link aqui-->
          </div>
        </div> <!--Fim header-->
        <!--Iniciando nova página-->
      
      <div class="row v-full">
          <div class="col-12">
              <h3 class="text-secondary mx-5 my-3">{{bloco}}</h3>
          </div>
          {% for p in pisos %}
            <div>
              <h6 class="font-weight-bold text-dark mx-5">{{p}}</h6>
            </div>
            <div class="card-body">
              
              <nav class="overflow-x-auto">
                <ul class="custom-ul mx-5">
                  {% for s in p.get_salas %}
                  <li>
                    <a href="/sala/{{s.id}}/"><img src="/media/{{s.imagem}}" alt="..." class="rounded-circle img-fluid" width="140" height="140"></a>
                    <h6 class="text-center py-2">{{s.nome}}</h6>
                    
                  </li>
                  {% empty %}
                  <li>
                      <h6 class="text-center py-2">Nenhuma sala cadastrada.</h6>
                  </li> 
                  {% endfor %}
                </ul>
              </nav>
              
            </div>
            
          </section>
       
          {% empty %}
          
              <h6 class="text-center py-2">Nenhum piso cadastrado</h6>
          
          {% endfor %}

      </div>


      <div class="row footer align-items-center py-4">
          <div class="col text-center px-5 text-dark">
            &copy; <span id="ano">2023</span> - IF Tour
          </div>
      </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous">


  </script>
    
{%endblock%}

espacos/templates/cadastro_adm.html
{%extends 'base.html'%}
{%load static %}
{%block conteudo%}
<div class="fundo d-flex justify-content-center align-items-center">
    <main class="w-100 m-auto formulario">
        <form method="post" enctype="multipart/form-data" action="{% url 'cadastro_adm' %}">
            <img src="{% static 'img/logo.png'%}" alt="" width="150" class="mb-4 mx-auto d-block">
            <div class="form-floating mb-3">
                <input type="text" name="nome" placeholder="Nome" class="form-control opacity-50" id="floatingInput">
                <label for="floatingInput">Nome</label>
            </div>
            <div class="form-floating mb-4">
                <input type="email" name="email" placeholder="Email" class="form-control opacity-50" id="floatingInput">
                <label for="floatingInput">Email</label>
            </div>
            <div class="form-floating mb-3">
                <input type="text" name="login" placeholder="Login" class="form-control opacity-50" id="floatingInput">
                <label for="floatingInput">Login</label>
            </div>
            <div class="form-floating mb-4">
                <input type="password" name="senha" placeholder="Senha" class="form-control opacity-50" id="floatingInput">
                <label for="floatingInput">Senha</label>
            </div>
            
            <div class="form-floating mb-3">
                <input type="file" name="foto" class="form-control opacity-50" id="fotoInput" accept="image/*">
                <label for="fotoInput">Foto</label>
            </div>

            {% csrf_token %}
            <button class="btn py-2 btn-success w-100 custom-btn">Cadastrar</button>
        </form>
    </main>
</div>
{%endblock%}

espacos/templates/index.html
{%extends 'base.html'%}
{%load static %}
{%block conteudo%}  
  <div>
        <div class="container-fluid">
          <div id="inicio" class="row v-full">
            <div class="col-12 col-sm-12 col-md-8 col-lg-6 align-self-center mx-auto text-center p-5">
                <a href="/">
                    <img class="img-fluid mx-auto p-2 logo-index" src="{% static 'img/logo.png'%}" alt="logo if-tour" width="200">
                </a>
                <p class="h2 p-4 my-4 texto-index">Explore o IFRN, campus São Paulo do Potengi, de maneira
                    totalmente <br> virtual, explorando o seu principal bloco, conhecendo suas salas, laboratórios e serviços.</p>
                <a href="bloco/" class="btn btn-dark btn-lg px-4 my-2 botao-acessar">Acessar</a>
            </div>
        </div>
        
            <div class="row">
              <div class="col-12 px-5">
                <h1 class="p-4 text-dark text-center custom-h1">IFRN - SPP</h1>
                <p class="h4 p-4 text-dark text-center">Explore o IFRN,  Campus São Paulo do Potengi, de maneira totalmente virtual, explorando os seus principais blocos, conhecendo suas salas, laboratórios e serviços.</p>
              </div>
              <div class="col-12 px-5">
                <ul class="custom-ul row justify-content-md-center text-center" >
                    {% for i in lista %}
                    <li class="col-lg-3">
            
                        <img class="rounded-circle" src="media/{{i.imagem}}" alt="{{i.nome}}" width="300" height="290">
                        <h5 class="text-dark">{{i.nome}}</h5>
                        <p class="text-dark p-2 h5">{{i.legenda}}</p>
                        <p><a class="btn btn-dark" href="bloco/{{b.bloco}}" role="button">Detalhar</a></p>
                    </li>
                      
                    {% empty %}
                    <li>
                        <h6 class="text-center py-2">Nenhum bloco cadastrado.</h6>
                    </li> 
                    {% endfor %}
                </ul>
              </div>
            </div>
            <div class="row footer align-items-center">
              <div class="col text-center px-5 text-dark">
                &copy; <span id="ano">2023</span> - IF Tour
              </div>
            </div>
          </div>
  {%endblock%}

espacos/templates/login_adm.html
{%extends 'base.html'%}
{%load static %}
{%block conteudo%}

<div class="fundo d-flex justify-content-center align-items-center">
    <main class="w-100 m-auto formulario">
        <form>
            <img src="{% static 'img/logo.png'%}" alt="" width="150" class="mb-4 mx-auto d-block">
            <div class="form-floating mb-3">
                <input type="text" placeholder="Login" class="form-control opacity-50" id="floatingInput">
                <label for="floatingInput">Login</label>
            </div>
            <div class="form-floating mb-4">
                <input type="password" placeholder="Senha" class="form-control opacity-50" id="floatingInput">
                <label for="floatingInput">Senha</label>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">Lembre-se de mim</label>
                </div>
                <p><a id="nao_tem_conta" href="cadastro_adm.html/">Não tenho conta criada</a></p>
            </div>
            <button class="btn py-2 btn-success w-100 custom-btn">Entrar</button>
        </form>
    </main>
</div>

{%endblock%}

espacos/templates/sala.html
{%extends 'base.html'%}
{%load static %}
{%block conteudo%}
<!--código que marcus fez peguei o código de pedrina e fiz as mudanças que precisavam-->

<div class=" col-8 imagem_360">        
  <a-scene background="color: #ECECEC">
    <a-assets>
      <img id="tste" src="/media/{{sala.img_360}}">
    </a-assets>
    <a-sky src="#tste"></a-sky>
  </a-scene>
</div>

<button class="btn btn-white sidebar mx-5" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions" id="trespontos"><i class="bi bi-justify text-dark" style="font-size: 30px"></i>hgy</button>

<div class="container-fluid">
<div class="row justify-content-end py-2">

<div class="col-12 col-md-8" id="botao-tab">
    
    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">

        <div class="col-12 border">
            <div class="offcanvas-header">
              <h4 class="offcanvas-title" id="offcanvasWithBothOptionsLabel"><strong>{{sala.nome}}</strong></h4>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="col-12 py-2">
                <ul class="justify-content-start">
                  <li class="mx-2">{{bloco.nome}}</li>
                  <li class="mx-2">{{piso.nome}}</li>
                </ul>
            </div>
        </div>

        <div class="offcanvas-body border">
            <p class="h6"><strong>Avaliação</strong></p>
            <h1 class="text-dark">
             {{media}}/5.0
           </h1>
                <div class="container mt-5">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active"  data-bs-toggle="tab" href="#sobre">Sobre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  data-bs-toggle="tab" href="#comentarios">Comentários</a>
                        </li>
                    </ul>
            
                    <div class="tab-content">
                        <div id="sobre" class="tab-pane active">
                            <p class="py-3">{{sala.legenda}}</p>
                        </div>
                        <div id="comentarios" class="tab-pane">
                         <ul class="text-dark listando h4 py-2">                    
                           {%for c in comentarios%}
                             <li style="text-decoration: none;">{{c.nome}}, {{c.comentario}}, {{c.nota}}, {{c.dt_cad}}</li>
                           {%endfor%}
                         </ul> 
                        </div>
                    </div>
                </div>
          </div>

          <div class="col-12">
            <div class="d-flex justify-content-between">

                <button id="bt-comentar" type="button" class="btn btn-secondary btn-lg m-4" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Avaliar
                </button> <!--vou mudar a aparencia quando tiver no django data do comentário 23-09-2023-->

                <a href="/">
                    <button class="btn btn-secondary btn-lg m-4">Sair <strong>X</strong></button>
                </a> <!--vou mudar a aparencia quando tiver no django data do comentário 23-09-2023-->
            </div>
          </div>
    </div>
</div>

<!--Links de voltar para página, entrar para adm, cadastrar adm-->
<div class="col-12 col-md-3 mx-2 justify-content-start" style="font-size: 18px;" id="links-secundarios">
    <ul class="opcoes">
        <li><a class="mx-4 text-dark botao-sala p-2" href="/">Inicio</a></li>
        <li><a class="mx-4 text-dark botao-sala p-2" href="{% url 'login_adm' %}">Entrar</a></li>
        <li><a class="mx-4 text-dark botao-sala p-2" href="{% url 'cadastro_adm' %}">Cadastrar</a></li>
    </ul>
</div>

<!--modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog mx-auto">
        <div class="modal-content">
            <div class="modal-header ">
                <h5 class="modal-title" id="exampleModalLabel">{{sala.nome}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="estrelas">
                        <input type="radio" id="cm_star-empty" name="fb" value="" checked/>
                        <label for="cm_star-1"><i class="fa"></i></i></label>
                        <input type="radio" id="cm_star-1" name="fb" value="1"/>
                        <label for="cm_star-2"><i class="fa"></i></label>
                        <input type="radio" id="cm_star-2" name="fb" value="2"/>
                        <label for="cm_star-3"><i class="fa"></i></label>
                        <input type="radio" id="cm_star-3" name="fb" value="3"/>
                        <label for="cm_star-4"><i class="fa"></i></label>
                        <input type="radio" id="cm_star-4" name="fb" value="4"/>
                        <label for="cm_star-5"><i class="fa"></i></label>
                        <input type="radio" id="cm_star-5" name="fb" value="5"/>
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput"></label>
                        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Nome">
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1"></label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Deixe seu comentário"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-success">Salvar comentário</button>
            </div>
        </div>
    </div>
</div>
</div>
{%endblock%}

espacos/templates/sala_exemplo.html
{%extends 'base.html'%}
{%load static %}
{%block conteudo%}
<!--código que Pedrina fez não mudei absolutamente nada!-->

<div class="container-fluid p-0 m-0">
  <div class="row">
    <div class="col-4">
     <div class="row align-items-center bm-0">
         <a href="/"> 
             <img class="img-fluid p-2 salasrounded"
             src="{% static '/img/logo.png'%}" alt="logo if-tour">
         </a>
     </div>
     <div class="row">
       <div class="container-fluid">
           <div class="row">
               <div class="col">
                 <h1 class="text-light">
                   {{sala.nome}}  - {{media}}/5.0
                 </h1>
               </div>
           </div>
           <div class="row">
               <div class="col-6">
                 <p class="text-light">
                   {{sala.legenda}}
                 </p>
               </div>
               <div class="col-6">
                 <h1 id="bt-comentar" class="btn btn-secondary btn-sm my-3" data-bs-toggle="modal" data-bs-target="#exampleModal">Adicionar Comentário</h1>
                 <ul class="text-light listando h4">                    
                   {%for c in comentarios%}
                     <li>{{c.nome}}, {{c.comentario}}, {{c.nota}}, {{c.dt_cad}}</li>
                   {%endfor%}
                 </ul>      
               </div>
           </div>
       </div>
     </div>
     <div class="row">
       <a id="blocoA" href="/piso/{{piso.id}}"> 
         <img class="img-fluid m-4" src="/media/{{bloco.imagem}}" alt="blocoA if-tour">
       </a>
     </div>
    </div>
    <div class="col-8">
      <!--<iframe id="c-360" class="row v-full"  width="100%" height="100%" allowfullscreen="yes" scrolling="no" allowvr="yes" src="/360/{{sala.id}}"></iframe>-->        
       <a-scene background="color: #ECECEC">
         <a-assets>
           <img id="tste" src="/media/{{sala.img_360}}">
         </a-assets>
         <a-sky src="#tste"></a-sky>
       </a-scene>
    </div>
  </div>
        
{%endblock%}